### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by vagabond12** [BGIResearch/SAW#10]
bash  stereoRun_multiLane_v4.1.0.sh
stereoRun_multiLane_v4.1.0.sh: line 8: syntax error near unexpected token `newline'
stereoRun_multiLane_v4.1.0.sh: line 8: `<!DOCTYPE html>'

I do not know what happened, please help me ,thank you.

I could not run this script.

**Comment by Clouate** [comment]
@vagabond12 It seems like input error or Unix coding error, please check your inputs, and avoid copying script content directly from this site to your Linux system
