### ISSUE TITLE
Generate indexed reference

### ISSUE THREAD

**Issue by kangbw702** [BGIResearch/SAW#11]
Hi, 

I tried to build indexed reference genome using mapping function: `singularity exec <SAW_v4.1.0.sif> mapping --runMode genomeGenerate --genomeDir ....` I received error: `Error for command "exec": unknown flag: --runMode`. It seems that mapping function does not have a run mode option. How can I check the function details in the container? 

Best,
Bowei

**Comment by Clouate** [comment]
It seems like error in your command line and mapping function has run mode option:
![微信图片_20220810182916](https://user-images.githubusercontent.com/58293762/183880001-b7010a0f-91a0-4488-aa89-b6b69098c6fd.png)
