### ISSUE TITLE
Error code: SAW-A10400

### ISSUE THREAD

**Issue by Dragonlongzhilin** [BGIResearch/SAW#12]
Hi, when I prepared the reference and encountered a problem.

This is my running code:
singularity exec SAW_v4.1.0.sif mapping \
--runMode genomeGenerate \
--genomeDir $referenceDir/human \
--genomeFastaFiles $referenceDir/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
 --sjdbGTFfile $referenceDir/genes/Homo_sapiens.GRCh38.107.gtf \
--sjdbOverhang 99 \
--runThreadN 24

the error is:
![image](https://user-images.githubusercontent.com/33304280/184627960-e32bc91d-3e19-4780-a861-b1bba429f5d0.png)

**Comment by Clouate** [comment]
Sorry for the late reply, we also found this error code in other problems, and found that the reasons are insufficient RAM and defective input files.You may try to set --limitGenomeGenerateRAM a higher value(like 170000000000).

**Comment by SeanZhi** [comment]
same error when running stereoRun_singleLane_v4.1.0.sh
<img width="551" alt="image" src="https://user-images.githubusercontent.com/40906340/188532165-ec75c7dc-3155-4496-bf37-8e463a9da34e.png">
any suggestion?

**Comment by Clouate** [comment]
> same error when running stereoRun_singleLane_v4.1.0.sh <img alt="image" width="551" src="https://user-images.githubusercontent.com/40906340/188532165-ec75c7dc-3155-4496-bf37-8e463a9da34e.png"> any suggestion?

Based on our experience, this error code is often due to incomplete input files(you may check your fastq, mask file or script etc.) or  insufficient RAM (set --limitBAMsortRAM ,--limitGenomeGenerateRAM or --outBAMsortingBinsN to higher values). For example, you can check your [DP8450002517TL_L01_read_1.Log.out] in directory 00.mapping to confirm how much RAM your analysis need.

**Comment by petitmingchang** [comment]
I got the sam error code when I mapped reads to genome with command and error message as follows:

singularity exec ~/NGS_tools/SAW_v5.1.3.sif mapping \
--outSAMattributes spatial \
--outSAMtype BAM SortedByCoordinate \
--genomeDir /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/STAR_SJ100 \
--runThreadN 8 \
--outFileNamePrefix /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01. \
--sysShell /bin/bash \
--stParaFile /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01.bcPara \
--readNameSeparator \" \" \
--limitBAMsortRAM 38582880124 \
--limitOutSJcollapsed 10000000 \
--limitIObufferSize=280000000 \
--outBAMsortingBinsN 50 \
> /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01_barcodeMap.stat

Error code: SAW-A10400
get signal:	11
/usr/local/bin/mapping: line 1: 89952 Segmentation fault      (core dumped) /opt/saw_v5.1.3_software/pipeline/mapping/mapping_v1.0.6 $*
