### ISSUE TITLE
Issue running the entire workflow using stereorun

### ISSUE THREAD

**Issue by OnkarMulay** [BGIResearch/SAW#15]
/opt/pipeline/mapping/bcStar_v1.0.3: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory

/opt/pipeline/merge/ST_BarcodeMap_v0.0.2: error while loading shared libraries: libboost_serialization.so.1.73.0: cannot open shared object file: No such file or directory

/opt/pipeline/count/Bam2Gem_v2.2.2: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory

What should be done in this case?

**Comment by Clouate** [comment]
@OnkarMulay Hello, you may try to run SAW with the newest version of singularity(>=3.8.1)

**Comment by OnkarMulay** [comment]
Thanks, I have successfully installed 3.5.0, will that do? Currently, I get some error with 3.5.0 version as well.

Error code: SAW-A10125
EXITING: FATAL INPUT ERROR: unrecognized parameter name "genomeType" in input "genomeParameters.txt"
SOLUTION: use correct parameter name (check the manual)

Please, may I know the solution to this?
Thanks

**Comment by Clouate** [comment]
> Thanks, I have successfully installed 3.5.0, will that do? Currently, I get some error with 3.5.0 version as well.
> 
> Error code: SAW-A10125 EXITING: FATAL INPUT ERROR: unrecognized parameter name "genomeType" in input "genomeParameters.txt" SOLUTION: use correct parameter name (check the manual)
> 
> Please, may I know the solution to this? Thanks

@OnkarMulay Yes, v3.5.0 did solve your last problem(error while loading shared libraries ...).
About error code: SAW-A10125, did you use indexed genome(input for parameter "-g" when running SAW) generated by other version of STAR? "genomeType" shouldn't be in the genomeParameters.txt generated by our SAW mapping.You may delete the line with "genomeType" in genomeParameters.txt and try again.
But I would recommend using the "genomeGenerate" function in "SAW mapping" to generate indexed genome to make sure the STAR versions are the same.
Example:
singularity exec SAW_v4.1.0.sif mapping --runMode genomeGenerate --genomeDir ... --genomeFastaFiles ... sjdbGTFfile ... --sjdbOverhang 99 --runThreadN ...

**Comment by OnkarMulay** [comment]
Ok, I shall try this and close the issue if it solves the error
