### ISSUE TITLE
Custom genome generation

### ISSUE THREAD

**Issue by maximelepetit** [BGIResearch/SAW#155]
Hi,

I'm working on a infected mouse lung by Influenza (H3N2).
My question is do you provide tutorial regarding custom genome generation ?
Bests

Maxime

**Comment by Jinghao-Chen** [comment]
Hi, you may need to prepare the required fasta files and corresponding gtf files. For example, merge the virus sequence's fasta into the mouse's fasta, and then refer to the following tutorial to build it
For SAW <v8.0:
https://github.com/STOmics/SAW/tree/main/Scripts/pre_buildIndexedRef
For SAW >=v8.0:
https://www.stomics.tech/service/new-saw-operation-manual.html or
https://en.stomics.tech/service/new-saw-operation-manual.html
`Tutorials->Preparation of reference`

**Comment by maximelepetit** [comment]
It works !
