### ISSUE TITLE
how to update ipr file 

### ISSUE THREAD

**Issue by lvmt** [BGIResearch/SAW#158]
i want to use the third part software to do cellsegmentation and when i get the mask file. how can i update the ipr file to do the next saw analysis.

**Comment by Jinghao-Chen** [comment]
@lvmt Hi, may I ask which version of SAW do you want to use?

**Comment by lvmt** [comment]
saw 7.1

**Comment by Jinghao-Chen** [comment]
SAW 7.1 does not provide the function of directly changing ipr, but you could refer to lines 508~563 in [Scripts/stereoPipeline_v7.1.sh](https://github.com/STOmics/SAW/blob/main/Scripts/stereoPipeline_v7.1.sh) to obtain the cellbin analysis results. You could input your cell segmentation result mask file by `cellCut cgef` through the -m parameter.

**Comment by lvmt** [comment]
ok, thanks and i will have a try. 

And I want to know if you will develop A method to segment cell according to cell wall; because this will be nice to plant sample.

**Comment by Jinghao-Chen** [comment]
We’re working on it, at present, the SAW cell segmentation algorithm is mainly trained on cell nucleus images. Some users told us that using SAW to process plant images (cell wall staining) can also produce good results, so you could have a try.

**Comment by lvmt** [comment]
recently, wo use stereo-chip to detect tomato and  we do the cell wall staining(FB28) on it;

I use imagestudio(v3) to do QC, stich, tissuecut and cell cut.  

**the cell cut result is weird, it cut the wall and think it as cell.** 

need your help and can U give me a advice to segment cell according to cell wall;

thanks.

**Comment by Jinghao-Chen** [comment]
Hi, It seems that you have used the manual cell segmentation module of ImageStudio. The cell segmentation algorithm in ImageStudio is the basic watershed algorithm, which has relatively poor results. You could try to use some third-party segmentation tools to process this image to see the segmentation result. For example, you could try Stereopy(https://stereopy.readthedocs.io/en/v1.4.0/Tutorials/Cell_Segmentation.html). The Deep Learning Model V3 in Stereopy is the latest cell segmentation algorithm model developed by the STOmics team. For FB staining, we have compared the algorithm effects and relatively recommend using Cellpose or Qupath.

**Comment by lvmt** [comment]
thanks, cellpose is useful and can solve my issue.
