### ISSUE TITLE
Segmentation fault (core dumped) error when use saw count 

### ISSUE THREAD

**Issue by nanlandetian** [BGIResearch/SAW#169]
command: `/share/soft/saw-8.1.2/bin/saw count --id NB1_saw_count --sn C04290D6 --omics=transcriptomics --kit-version="Stereo-seq T FF V1.2" --sequencing-type "PE100_50+100" --chip-mask=IDBHT-HNHZ-0168_20240826/mask/C04290D6.barcodeToPos.h5 --organism=human --tissue=skin --fastqs=IDBHT-HNHZ-0168_20240826/WS-NB-1-1 --reference=/share/pub/human/ensembl_GRCh38/transcriptome --image IDBHT-HNHZ-0168_20240826/image/C04290D6_ssDNA.tif`

SAW_VERSION: 8.1.2

 error:

> Error message: /bin/sh: line 1: 1638495 Segmentation fault      (core dumped) /share/soft/saw-8.1.2/lib/bcstar/bcSTAR --outSAMattributes spatial --outSAMtype BAM SortedByCoordinate --sysShell /bin/bash --limitBAMsortRAM 63168332971 --limitOutSJcollapsed 10000000 --limitIObufferSize=280000000 --outBAMsortingBinsN 50 --readNameSeparator " " --genomeDir /share/pub/human/ensembl_GRCh38/transcriptome/STAR/ --runThreadN 10 --outFileNamePrefix /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1. --stParaFile /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1.bcPara > /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1.run.log 2>> /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/log_map

detail log:
[log.txt](https://github.com/user-attachments/files/18109681/log.txt)

how can i solve this problem? thanks

**Comment by Jinghao-Chen** [comment]
Hi, could you provide `STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1.run.log`, and `STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/log_map`?
And was the reference you used generated by `saw makeRef`?

**Comment by nanlandetian** [comment]
thanks for your reply, the refrenence was download form ensembl, and the command are: `/share/soft/saw-8.1.2/bin/saw makeRef --mode=STAR --fasta=Homo_sapiens.GRCh38.dna.primary_assembly.fa --gtf=Homo_sapiens.GRCh38.113.gtf --genome=./transcriptome`;
the E100081315_L01_81_1.run.log are:
```
--- cmd:  /share/soft/saw-8.1.2/lib/bcstar/bcSTAR --outSAMattributes spatial --outSAMtype BAM SortedByCoordinate --sysShell /bin/bash --limitBAMsortRAM 63168332971 --limitOutSJcollapsed 10000000 --limitIObufferSize=280000000 --outBAMsortingBinsN 50 --readNameSeparator   --genomeDir /share/pub/human/ensembl_GRCh38/transcriptome/STAR/ --runThreadN 10 --outFileNamePrefix /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1. --stParaFile /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/E100081315_L01_81_1.bcPara

--- compile: 20240911
--- Info: v3.2.3 (based on STAR 2.7.2b) is released after optimization by STOmicsTech
--- Info: Max open files            1024                 262144               files     
Dec 12 18:02:11 ..... started bcSTAR run
--- Info: read-1 /share/workdir/yangl/work/Stereo_seq_AGA/IDBHT-HNHZ-0168_20240826/WS-NB-1-1/E100081315_L01_81_1.fq.gz
--- Info: read-2 /share/workdir/yangl/work/Stereo_seq_AGA/IDBHT-HNHZ-0168_20240826/WS-NB-1-1/E100081315_L01_81_2.fq.gz
--- Info: load mask file:/share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/C04290D6.barcodeToPos.h5......
--- Info: time for creating barcode map - 46 s, size of bcmap - 395172707
Dec 12 18:02:59 ..... loading genome
--- Info: time for loading index - 24.3333 s , the index occupy 41.0098 GB
--- Info: time for loading index and barcode map - 71.6545 s 	1.19424 min 
Dec 12 18:03:23 ..... started mapping
```
and the log_map is an empty file (.txt extention is add for attach file)
[E100081315_L01_81_1.run.log](https://github.com/user-attachments/files/18119408/E100081315_L01_81_1.run.log)
[log_map](https://github.com/user-attachments/files/18119420/log_map.txt)

**Comment by Jinghao-Chen** [comment]
@nanlandetian Hi, could you check the integrity of the fastq file? For example, use `zcat /path/to/E100081315_L01_81_*.fq.gz | tail `to check if the 'unexpected end of file' message is output. In addition, it is recommended to execute the following code before running the SAW `ulimit -n 262144`

**Comment by nanlandetian** [comment]
@Clouate thank for your response, I have checked MD5 hashcode after I download the data(all is OK), The E100081315_L01_81_*.fq.gz file tail is :
```
[yang@localhost WS-NB-1-1]$ zcat E100081315_L01_81_1.fq.gz | tail
+
35EFDE4BF;G:EFG8,F3:,@EFGG><G=-AFFF
@E100081315L1C042R04104429968/1
GCTGTCTCTTATACACATCTTCTGCTCTTACTCAC
+
GGGGGGGGGGGGGGGGGGFDGGGHGGG,GFGDFFG
@E100081315L1C042R04104430212/1
GGAATTCGCACTATGTCTCGGAAGGCTTCTTCTGC
+
<:BGBBB.HBABBBBGGE75FFF@GFABDI<FCBE
[yang@localhost WS-NB-1-1]$ zcat E100081315_L01_81_2.fq.gz | tail
+
FFFGEGAFFGGGG=G3FAFG<FC@GGFGGGFDGGFBGD5GGFAF(F=FEECFGFG@FFDG;DFC+GAF>F93FF9GD6E+EG9FD2E,EE3E=,G-C;0)
@E100081315L1C042R04104429968/2
CCTGATAAGGTCGCCATGCCTCTCAGTACGTCAGCAGAAGCAGTGGTATCAACGCACAGTACATGCGTGAGTATGAGACGTTCTCCACTCAGCAGGAGGT
+
GGFGGHGGGGGGFGGGGEGFGGGGFGIIGFGGGGGFGDGGGG)BAGFFICGGGGGG(GGGEG>GGGABGGGCEGG>D5FEDFFFG+,GGG6?FFC+FF,G
@E100081315L1C042R04104430212/2
ACCTTCCGAGACATAGTGCGAATTCCCTGATAAGGTCGCCATGCCTCTCAGTACGTCAGCAGAAGCAGTGGTATCAACGCAGAGTACATGCGTGAGTATG
+
6GIEIBBEGCFGBICH;FH?BIH;FGG4HFF<FGGGGAGGFF6@IEG:G>G?3F,GGFEF:F:GGDFGEFHFCCFFFFFCD=B947G=7G1=FFBCE=DF
```
and I try to run  `ulimit -n 262144` before running the SAW count ,the error still the same.

**Comment by Jinghao-Chen** [comment]
Can I know how much memory is available when you run the SAW, as shown by the `free -g` output? Have you successfully used SAW to analyze other data on your Linux server before?

**Comment by nanlandetian** [comment]
it is the first time I run the saw , I have not successfully go throuw the pipeline before,  my linux server have 1.5 T  memory,and have over 1.1T memory available.

**Comment by Jinghao-Chen** [comment]
Could you try to add these two parameters to saw count `--threads-num 24 --memory 200` and run it again? Before running, you can use `free -h` to ensure that the running memory is sufficient.

**Comment by nanlandetian** [comment]
@Clouate when I run with `--threads-num 24 --memory 200`(`ulimit -n 262144` before `saw count`), the error is the same,detail log are attaced below (my linux system is centos 8).  
```
[yangl@localhost Stereo_seq_AGA]$ ulimit -n 262144
[yangl@localhost Stereo_seq_AGA]$ free -h
              total        used        free      shared  buff/cache   available
Mem:          1.5Ti        18Gi       328Gi       342Mi       1.1Ti       1.4Ti
Swap:         4.0Gi       4.0Gi       0.0Ki
[yangl@localhost Stereo_seq_AGA]$ /share/soft/saw-8.1.2/bin/saw count --id=NB1_saw_count --sn=C04290D6 --omics=transcriptomics --kit-version="Stereo-seq T FF V1.2" --sequencing-type="PE100_50+100" --chip-mask=IDBHT-HNHZ-0168_20240826/mask/C04290D6.barcodeToPos.h5 --organism=human --tissue=skin --fastqs=IDBHT-HNHZ-0168_20240826/WS-NB-1-1 --reference=/share/pub/human/ensembl_GRCh38/transcriptome --image=IDBHT-HNHZ-0168_20240826/image/C04290D6_ssDNA.tif --threads-num=24 --memory=200
execute:  snakemake -c 24 -s /share/soft/saw-8.1.2/config/count.smk --configfile /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/pipeline-logs/config.yaml -d .snakemake_yangl --rerun-incomplete --rerun-triggers mtime >/share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/pipeline-logs/log 2>&1
The program execution encountered an issue and has exited.Please check the log file: /share/workdir/yangl/work/Stereo_seq_AGA/NB1_saw_count/pipeline-logs/log

```
[log.txt](https://github.com/user-attachments/files/18143788/log.txt)
[log_map.txt](https://github.com/user-attachments/files/18143789/log_map.txt)
[E100081315_L01_81_1.run.log](https://github.com/user-attachments/files/18143790/E100081315_L01_81_1.run.log)


Is it possible that saw preferentially called some incompatible libraries form other software (such as cellranger) that caused the error? Here are my current environment variables:
```
[yangl@localhost Stereo_seq_AGA]$ $PATH
bash: /share/soft/python-3.11.0/bin/:/share/workdir/yangl/miniconda3/condabin:/share/workdir/yangl/.local/bin:/share/workdir/yangl/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/share/soft/R-4.1.3/bin:/share/soft/jdk-16.0.1/bin:/share/soft/cellranger-7.1.0/bin:/share/soft/samtools-1.13/bin:/share/soft/dotnet: No such file or directory
```

**Comment by Jinghao-Chen** [comment]
It seems that your Linux system has an abnormal swap free of 0.0Ki. Could you contact the system administrator to adjust it? We have tested these softwares(such as cellranger) environments and have not encountered the libraries conflict problem. Or you could try to temporarily block the existing $PATH variable, or try a clean environment, such as a conda empty environment.
And could you display the output of `ulimit -a` and send me the file `E100081315_L01_81_1.Log.out`?

**Comment by nanlandetian** [comment]
I just download the Demo_Mouse_Brain data (sn:C04042E3) ,and use `reference-data-mouse_SAW_v8.tar.gz` as the reference. when run the Demo data,I have successfully go through the `bcSTAR` step which encounter Segmentation fault error, so I suspect there might be an issue with the reference genome I used. My human reference genome was constructed using the latest genome and GTF annotation files downloaded from Ensembl(https://ftp.ensembl.org/pub/release-113/fasta/homo_sapiens/dna/), and the construction log file is attached below(reference constructed successfully). Could you provide me with a human reference that supports SAW v8.1 so I can test it?

[makeRef Log.out.txt](https://github.com/user-attachments/files/18147085/Log.out.txt)

**Comment by Jinghao-Chen** [comment]
@nanlandetian Hi, I have downloaded the .fasta and .gtf from the Ensembl link, and construct the reference. And I have successfully run the pipeline, you could use it and have a try. By the way, you could also use reference-data-mouse_SAW_v8 as a reference to analyze your data for a test.
link： http://116.6.21.110:8090/share/fbf31a2b-152f-4ca7-8c78-4d0eee53b1f7
password： ceGN

**Comment by nanlandetian** [comment]
Thanks,the error have solved by use your human reference data (reference-data-mouse_SAW_v8 can also completed saw count successfully )
