### ISSUE TITLE
Image registration problem of histological images and gene expression images

### ISSUE THREAD

**Issue by wenjiecai** [BGIResearch/SAW#17]
Hello,
when I'm trying to use the axolotl data on the websites of BGI spatiotemporal omics (https://db.cngb.org/stomics/artista/download.html) for tissue segmentation, I found the image data (such as:  https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/2DPI_1.tif) and gene expression data(https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/2DPI_1.gem.gz) don't seem to be registered. 

I checked the paper, mentioned that the author performed the alignment manually. I run the docker of SAW(V 2.1.0) and found there is a tool called "manualregister", but I don't found the user manual for SAW(V 2.1.0) ，don't know the required input parameters.

I want to know SAW(V 2.1.0) can register gems with tifs, could you please provide the user manual of SAW(V 2.1.0)

**Comment by TheSallyGardens** [comment]
Hi,please check this link:https://github.com/BGIResearch/stereopy/issues/79#issuecomment-1278596072

**Comment by TheSallyGardens** [comment]
Hello, let me test it first.https://github.com/BGIResearch/stereopy/issues/79#issuecomment-1279641162

**Comment by TheSallyGardens** [comment]
@wenjiecai  Hi！We found the problem and gave the following solutions.
First download the beta version SAW4.1.0（https://hub.docker.com/r/stomics/saw_beta/tags).
Second, decompress and modify the MIDCounts in the gem file to MIDCount.
Finally, modify the name of 10DPI_1.gem to barcode_gene.exp.txt.
Then you can use the registration function of saw.
Best wishes!

**Comment by wenjiecai** [comment]
> @wenjiecai Hi！We found the problem and gave the following solutions. First download the beta version SAW4.1.0（https://hub.docker.com/r/stomics/saw_beta/tags). Second, decompress and modify the MIDCounts in the gem file to MIDCount. Finally, modify the name of 10DPI_1.gem to barcode_gene.exp.txt. Then you can use the registration function of saw. Best wishes!

Thank you for your help, I'll try it later

**Comment by wenjiecai** [comment]
> > @wenjiecai Hi！We found the problem and gave the following solutions. First download the beta version SAW4.1.0（https://hub.docker.com/r/stomics/saw_beta/tags). Second, decompress and modify the MIDCounts in the gem file to MIDCount. Finally, modify the name of 10DPI_1.gem to barcode_gene.exp.txt. Then you can use the registration function of saw. Best wishes!
> 
> Thank you for your help, I'll try it later

hi,  I have successfully registered most of the slice images with the method you provided, but there are still eight slices with some problems in registration. I hope to get your help.
【1】15DPI_3 and Meta Image registration results are incorrect.
【1.1】15DPI_3 
           image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_3.tif
           gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_3.gem.gz
           Registration image result：
![15DPI_3 regist error](https://user-images.githubusercontent.com/33197950/197317299-962aac14-0ff5-4993-ae5d-c24e36ee1ceb.png)
  【1.2】 Meta
          image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Meta.tif
          gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Meta.gem.gz
           Registration image result：
![Meta](https://user-images.githubusercontent.com/33197950/197317363-db1342c6-fec8-4197-b324-ef60cddf7a1c.png)

【2】Error in image registration  (Adult slice)
          image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Adult.tif
          gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Adult.gem.gz
          error:
<img width="1679" alt="Adult_error" src="https://user-images.githubusercontent.com/33197950/197317550-aa3efdd5-392c-409d-903c-9b6cf8bf512a.png">
  
【3】ImageQC report error
 【3.1】QC error (Stage44 and Stage54)
  image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage44.tif
  gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage44.gem.gz
  Stage44 error:
![Stage44](https://user-images.githubusercontent.com/33197950/197317696-d881f987-98be-4da6-88ad-e438ba5210cd.png)

  image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage54.tif
  gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage54.gem.gz
  Stage54 error:
 ![Stage54](https://user-images.githubusercontent.com/33197950/197317750-739c28b8-6834-4dd1-a5f0-4633ae566000.png)

【3.2】QC Failed (15DPI_1,15DPI_2 and Stage57)
 I'm wondering if an image has a qc score below 0.5, does it mean that the image is completely unusable for registration.
 15DPI_1 failed qc:
![15DPI_1](https://user-images.githubusercontent.com/33197950/197317917-1e207402-4c7c-4f50-96ab-52dfe46b35a5.png)
15DPI_2 failed qc:
![15DPI_2](https://user-images.githubusercontent.com/33197950/197317929-33661324-a7e5-47d9-aceb-fed9dbef5ac2.png)
Stage57 failed qc:
![Stage57](https://user-images.githubusercontent.com/33197950/197317943-41aec6d0-2f50-46b6-9075-1b1d6bceb675.png)

image link:
15DPI_1: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_1.tif
15DPI_2: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_2.tif 
Stage57: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage57.tif

gem link:
15DPI_1: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_1.gem.gz
15DPI_2: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_2.gem.gz
Stage57: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage57.gem.gz

thanks for your help!

**Comment by wenjiecai** [comment]
> @wenjiecai Hi！We found the problem and gave the following solutions. First download the beta version SAW4.1.0（https://hub.docker.com/r/stomics/saw_beta/tags). Second, decompress and modify the MIDCounts in the gem file to MIDCount. Finally, modify the name of 10DPI_1.gem to barcode_gene.exp.txt. Then you can use the registration function of saw. Best wishes!

hi, I have successfully registered most of the slice images with the method you provided, but there are still eight slices with some problems in registration. I hope to get your help.

【1】15DPI_3 and Meta Image registration results are incorrect.
【1.1】15DPI_3
image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_3.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_3.gem.gz
Registration image result：
![15DPI_3 regist error](https://user-images.githubusercontent.com/33197950/197318339-40e4ead9-8a59-4e04-9694-fc9ebaa28927.png)

【1.2】 Meta
image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Meta.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Meta.gem.gz
Registration image result：
![Meta](https://user-images.githubusercontent.com/33197950/197318911-9b282e33-080b-44f0-8dcf-3ac6d2619ecd.png)

【2】Error in image registration (Adult slice)
image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Adult.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Adult.gem.gz
error:
<img width="1679" alt="Adult_error" src="https://user-images.githubusercontent.com/33197950/197318919-a0b432d4-44d2-43f2-b4ed-295f34670639.png">

【3】ImageQC report error
【3.1】QC error (Stage44 and Stage54)
image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage44.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage44.gem.gz
Stage44 error:
![Stage44](https://user-images.githubusercontent.com/33197950/197319051-fb96bf4f-bc19-400d-af30-60a024930e22.png)

image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage54.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage54.gem.gz
Stage54 error:
![Stage54](https://user-images.githubusercontent.com/33197950/197319026-ac288d22-2db2-4084-b16c-679d0c0043a8.png)

【3.2】QC Failed (15DPI_1, 15DPI_2 and Stage57)
I'm wondering if an image has a qc score below 0.5, does it mean that the image is completely unusable for registration.
15DPI_1 failed qc:
![15DPI_1](https://user-images.githubusercontent.com/33197950/197319070-5d36d116-39c5-4420-a055-d9ca25d407a2.png)
15DPI_2 failed qc:
![15DPI_2](https://user-images.githubusercontent.com/33197950/197319082-a38cd7ae-307d-4979-8002-e59336c174f0.png)
Stage57 failed qc:
![Stage57](https://user-images.githubusercontent.com/33197950/197319096-307dea81-8c5e-4a97-98de-a89c68c42a55.png)

image link:
15DPI_1: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_1.tif
15DPI_2: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/15DPI_2.tif
Stage57: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Stage57.tif

gem link:
15DPI_1: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_1.gem.gz
15DPI_2: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/15DPI_2.gem.gz
Stage57: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Stage57.gem.gz

thanks for your help!

**Comment by wenjiecai** [comment]
> @wenjiecai Hi！We found the problem and gave the following solutions. First download the beta version SAW4.1.0（https://hub.docker.com/r/stomics/saw_beta/tags). Second, decompress and modify the MIDCounts in the gem file to MIDCount. Finally, modify the name of 10DPI_1.gem to barcode_gene.exp.txt. Then you can use the registration function of saw. Best wishes!

hi, I have found that the error in Adult slice registration is because my server is out of memory, but when I replaced another server with larger memory, I found that the final image registration result is still incorrect.

raw tif image:
<img width="596" alt="raw_Adult_image" src="https://user-images.githubusercontent.com/33197950/197394361-02a3cb3e-192c-403a-8dbe-396e081d9c38.png">
gene scatter plot:
<img width="1121" alt="gene_scatter" src="https://user-images.githubusercontent.com/33197950/197394387-d6f530f1-71fc-41f3-a906-f842b600f1f0.png">
registration result image:
<img width="477" alt="register_result" src="https://user-images.githubusercontent.com/33197950/197394423-a0b4be6e-751f-4f50-9e72-592ab7eef643.png">

image link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Image/Adult.tif
gem link: https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000056/Bin1_matrix/Adult.gem.gz

**Comment by TheSallyGardens** [comment]
Hi,If QC fails, please consult the imageQC(https://github.com/BGIResearch/imageQC).
Alternatively, please contact the author of the article to obtain the registered image

**Comment by wenjiecai** [comment]
> Hi,If QC fails, please consult the imageQC(https://github.com/BGIResearch/imageQC). Alternatively, please contact the author of the article to obtain the registered image

Thank you
