### ISSUE TITLE
SAW pipeline not progressing at the annotation step

### ISSUE THREAD

**Issue by Nakyung210** [BGIResearch/SAW#170]
Hello,

I've running the SAW count but it's been stagnant at the annotation part for almost a week... (below image is the log_anno from STEREO_ANALYSIS_WORKFLOW_PROCESSING/ANNOTATION)
![Capture](https://github.com/user-attachments/assets/4bfe4d80-8c7c-410e-9ceb-80b784575d14)

I didn't get any error message so I could not figure out what went wrong. Could you help?

Thanks in advance!

**Comment by Jinghao-Chen** [comment]
@Nakyung210 Hi, there is a bug in SAW, that is, when the gtf file contains extra chromosomes that do not belong to the header of STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/bam(`samtools view -H STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/bam`), the program will get stuck. Could you confirm this by checking your gtf file? Additionally, you could check if the space of the device is sufficient.

**Comment by Nakyung210** [comment]
Thank you. I checked the bam file and gtf file. As you suggested, gtf file contained extra chromosomes which are not included in the bam files. So I've tried to create new reference with filtered gtf file. "checkGTF" has no issue with running
![Capture2](https://github.com/user-attachments/assets/80733187-b952-41c0-9f3b-8e824bee7cb4)
, but when I run the "makeRef", I kept getting this error message saying "Warning: The sequence cannot be exactly equal.":
![Capture](https://github.com/user-attachments/assets/e61df234-81fc-4fba-ad45-0e40693233f3)

I couldn't find any documentation mentioning what this error message mean. Could you help?

Thank you!

**Comment by Jinghao-Chen** [comment]
@Nakyung210 Hi, Could you provide the file `Log.out` in the directory you ran the `makeRef`? Didn't this error occur when you use original unfiltered gtf? 
If you have built the reference before, you could replace the gtf file in the /path/to/reference/genes/ directory with the filtered gtf file and re-run SAW.

**Comment by Nakyung210** [comment]
Thank you so much! 

I filtered the extra chromosome from previously generated /path/to/reference/genes/ gtf file and run makeRef with it. This time it didn't throw the error and worked. 

To follow up the original issue, I run the SAW count with newly created filtered gtf and it worked!! 

Thanks a lot for the help!
