### ISSUE TITLE
Error code: SAW-A10160

### ISSUE THREAD

**Issue by petitmingchang** [BGIResearch/SAW#19]
Hi,

I am a novice at using SAW.
I would like to build index for reference genome, the example shown in README.md.
However, it always returns a fatal error as following:

singularity exec SAW_v5.1.3.sif mapping \
--runMode genomeGenerate \
--genomeDir /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/STAR_SJ100_2 \ 
--genomeFastaFiles /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/genome.fa \ 
--sjdbGTFfile /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/genes.gtf \ 
--sjdbOverhang 99 \
--runThreadN 12 &

2022-10-26  16:42:44 ..... started STAR run
Oct 26 16:42:44 ... starting to generate Genome files
Error code: SAW-A10160

EXITING because of INPUT ERROR: could not open genomeFastaFile: /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/genome.fa

Oct 26 16:42:44 ...... FATAL ERROR, exiting

I am sure that those files are exist because it works when I run the command, "less /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/genome.fa", to see the content.

Thank you so much for your help.

petitming

**Comment by Clouate** [comment]
Hi, @petitmingchang ,you need to mount the related path when running singularity.
For example, run the following commands before running singularity:
referenceDir=/nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/
export SINGULARITY_BIND=$referenceDir

Please refer to https://github.com/BGIResearch/SAW/tree/main/script/pre_buildIndexedRef

referenceDir=/Full/Path/Of/Reference/Folder/Path
export SINGULARITY_BIND=$referenceDir

**Comment by petitmingchang** [comment]
Hi @Clouate ,

Thank you so much for your prompt reply.
It works fine now.

petitming
