### ISSUE TITLE
Error code: SAW-A10400 when mapping reads to genome

### ISSUE THREAD

**Issue by petitmingchang** [BGIResearch/SAW#20]
I got the sam error code when I mapped reads to genome with command and error message as follows:

singularity exec ~/NGS_tools/SAW_v5.1.3.sif mapping \
--outSAMattributes spatial \
--outSAMtype BAM SortedByCoordinate \
--genomeDir /nfs/NAS/single_cell_data/STOmics/SS200000135TL_D1/reference/STAR_SJ100 \
--runThreadN 8 \
--outFileNamePrefix /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01. \
--sysShell /bin/bash \
--stParaFile /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01.bcPara \
--readNameSeparator \" \" \
--limitBAMsortRAM 38582880124 \
--limitOutSJcollapsed 10000000 \
--limitIObufferSize=280000000 \
--outBAMsortingBinsN 50 \

Error code: SAW-A10400
get signal:	11
/usr/local/bin/mapping: line 1: 89952 Segmentation fault      (core dumped) /opt/saw_v5.1.3_software/pipeline/mapping/mapping_v1.0.6 $*

Is it also because of the RAM setting?

_Originally posted by @petitmingchang in https://github.com/BGIResearch/SAW/issues/12#issuecomment-1292895454_

**Comment by Clouate** [comment]
Hi, @petitmingchang .It is possible that there are empty lines in the .bcpara file: /nfs/NAS/single_cell_data/STOmics/output/00.mapping/E100026571_L01.bcPara
Could you delete the empty lines in the .bcpara file and try again?

**Comment by petitmingchang** [comment]
@Clouate

Yes, it works fine now after deleting the empty lines in the .bcPara file.
Thank you so much for your help.
