### ISSUE TITLE
test data can not be downloaded

### ISSUE THREAD

**Issue by yliuphys** [BGIResearch/SAW#23]
rnysyc seems not work to dowload the test data to server. Try with wget -r, but still not work. Could you please provide the host, User, Password, port, et al so that I can download the test data folder with wget. Thanks!

**Comment by TheSallyGardens** [comment]
![image](https://user-images.githubusercontent.com/40382381/206349762-4a1a01c9-c87e-4ba6-b93e-08a89891e003.png)
Hi! I can download normally using syc.Please try again.

**Comment by yliuphys** [comment]
Hi,
Thanks for double check. However, the rsync still not work to me:
Yong
    On Wednesday, December 7, 2022 at 09:31:14 PM CST, thesallygardens ***@***.***> wrote:  
 
 



Hi! I can download normally using syc.Please try again.
