### ISSUE TITLE
How to debug using SAW_v5 version?

### ISSUE THREAD

**Issue by Feng-Zhang** [BGIResearch/SAW#24]
Hi, I ran the whole pipeline based on SAW_v5 version, but got the error:
```
2022年 12月 16日 星期五 15:42:54 CST  singularity check: pass and path is /usr/bin/singularity
2022年 12月 16日 星期五 15:42:54 CST   visualSif check: file does not exists, please verify that your visualSif file in the current directory or the path given by the option -s is correct.
mkdir: 缺少操作数
请尝试执行 "mkdir --help" 来获取更多信息。
1_saw_test.sh: 行 26: -speciesName：未找到命令
1_saw_test.sh: 行 31: -imageCompressedFile：未找到命令
1_saw_test.sh: 行 32: -sif：未找到命令
1_saw_test.sh: 行 35: -outDir：未找到命令
```
The script I used is shown below:
```
ulimit -n 10240
ulimit -v 33170449147
export NUMBA_CACHE_DIR=/media/duo36t/test/SAW-pipeline

dataDir=/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5
outDir=/media/duo36t/test/SAW-pipeline/result

export SINGULARITY_BIND=$dataDir,$outDir
bash /media/duo36t/test/SAW/script/stereoPipeline.sh \
    -genomeSize 5 \
    -splitCount 1 \
    -maskFile $dataDir/mask/SS200000135TL_D1.barcodeToPos.h5 \
    -fq1 $dataDir/reads/E100026571_L01_trim_read_1.fq.gz,...,$dataDir/reads/E100026571_L01_trim_read_1.fq.gz  \
    -fq2 $dataDir/reads/E100026571_L01_trim_read_2.fq.gz,...,$dataDir/reads/E100026571_L01_trim_read_2.fq.gz \ # [optional] when the sequenced data is in PE format
    -speciesName mouse \
    -tissueType brain \
    -refIndex $dataDir/reference/STAR_SJ100 \
    -annotationFile $dataDir/reference/genes.gtf \
    -imageRecordFile $dataDir/image/SS200000135TL_D1_20220527_201353_1.1.0.ipr \ # [optional] when image is given and has passed QC
    -imageCompressedFile $dataDir/image/SS200000135TL_D1_20220527_201353_1.1.0.tar.gz \ # [optional] when image is given and has passed QC
    -sif /media/duo36t/reference/SAW_v5.4.0.sif \
    -threads 16 \
    -doCellBin Y \ # [optional] when you want to do the cell segmentation and get cell gene expression data
    -outDir $outDir
```

I guess there is a bug from stereoPipeline.sh, so I want to run step by step. For the first splitmask step, I got an error :
```
$ singularity exec /media/duo36t/reference/SAW_v5.4.0.sif splitMask $dataDir/mask/SS200000135TL_D1.barcodeToPos.h5 ${outDir}/00.splitmask  8 16 2_25
Error,cannot write to file,/media/duo36t/test/SAW-pipeline/result/00.splitmask/01.SS200000135TL_D1.barcodeToPos.bin
```

**Comment by TheSallyGardens** [comment]
Hi.Before running the splitMask module, you need to transfer SS200000135TL_ D1. barcodeToPos. h5 file  mount to container.
And Can you show me the stereoPipeline.sh?

**Comment by TheSallyGardens** [comment]
@Feng-Zhang If you use saw5.4.0, please use stereoPipeline_ v5.4.0.sh.

**Comment by Feng-Zhang** [comment]
Thank you for your reply. 
The stereoPipeline.sh is the [bash code](https://github.com/BGIResearch/SAW/blob/main/script/stereoPipeline.sh) from SAW git repository.
I change to run [stereoPipeline_v5.4.0.sh](https://github.com/BGIResearch/SAW/blob/main/script/stereoPipeline_v5.4.0.sh), and get similar error :
```
2022年 12月 21日 星期三 22:21:30 CST  singularity check: pass, and singularity path is /usr/bin/singularity
2022年 12月 21日 星期三 22:21:30 CST  singularity image file check: file does not exist, please double check your SIF file is in the current directory or the path given by the option -s is valid.
mkdir: 缺少操作数
请尝试执行 "mkdir --help" 来获取更多信息。
1_saw_test.sh: 行 26: -speciesName：未找到命令
1_saw_test.sh: 行 31: -imageCompressedFile：未找到命令
1_saw_test.sh: 行 32: -sif：未找到命令
1_saw_test.sh: 行 35: -outDir：未找到命令
```

**Comment by TheSallyGardens** [comment]
> Thank you for your reply. The stereoPipeline.sh is the [bash code](https://github.com/BGIResearch/SAW/blob/main/script/stereoPipeline.sh) from SAW git repository. I change to run [stereoPipeline_v5.4.0.sh](https://github.com/BGIResearch/SAW/blob/main/script/stereoPipeline_v5.4.0.sh), and get similar error :
> 
> ```
> 2022年 12月 21日 星期三 22:21:30 CST  singularity check: pass, and singularity path is /usr/bin/singularity
> 2022年 12月 21日 星期三 22:21:30 CST  singularity image file check: file does not exist, please double check your SIF file is in the current directory or the path given by the option -s is valid.
> mkdir: 缺少操作数
> 请尝试执行 "mkdir --help" 来获取更多信息。
> 1_saw_test.sh: 行 26: -speciesName：未找到命令
> 1_saw_test.sh: 行 31: -imageCompressedFile：未找到命令
> 1_saw_test.sh: 行 32: -sif：未找到命令
> 1_saw_test.sh: 行 35: -outDir：未找到命令
> ```
It seems that there is an incorrect syntax in 1_saw_test.sh, and there should be no spaces or comments after the slash.

**Comment by Feng-Zhang** [comment]
Thank you. It works. But I have another error:
```
2022年 12月 24日 星期六 08:33:40 CST  singularity check: pass, and singularity path is /usr/bin/singularity
2022年 12月 24日 星期六 08:33:40 CST  singularity image file check: file exist and SIF path is /media/duo36t/reference/SAW_v5.4.0.sif
2022年 12月 24日 星期六 08:33:40 CST => splitMask, compute CID count and predict the memory of mapping start......
WARNING: While bind mounting '/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reference:/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reference': destination is already in the mount point list
Your sequencing reads are in PE format.
2022年 12月 24日 星期六 08:34:02 CST => CID mapping, adapter filtering and RNA alignment start......
 ~~~ mapping - E100026571_L01_trim_read_1.fq.gz ~~~
WARNING: While bind mounting '/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reads:/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reads': destination is already in the mount point list
WARNING: While bind mounting '/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reference:/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reference': destination is already in the mount point list
 ~~~ mapping - ... ~~~
FATAL:   container creation failed: unable to add /media/duo36t/test/SAW-pipeline to mount list: destination must be an absolute path
```
The script I used is : 
```
ulimit -n 10240
ulimit -v 33170449147
export NUMBA_CACHE_DIR=/media/duo36t/test/SAW-pipeline/cache/

dataDir=/media/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5
outDir=/media/duo36t/test/SAW-pipeline/result

export SINGULARITY_BIND=$dataDir,$outDir,/media/duo36t/
bash /media/duo36t/test/SAW/script/stereoPipeline_v5.4.0.sh \
    -genomeSize 5 \
    -splitCount 1 \
    -maskFile $dataDir/mask/SS200000135TL_D1.barcodeToPos.h5 \
    -fq1 $dataDir/reads/E100026571_L01_trim_read_1.fq.gz,...,$dataDir/reads/E100026571_L01_trim_read_1.fq.gz \
    -fq2 $dataDir/reads/E100026571_L01_trim_read_2.fq.gz,...,$dataDir/reads/E100026571_L01_trim_read_2.fq.gz \
    -speciesName mouse \
    -tissueType brain \
    -refIndex $dataDir/reference/STAR_SJ100 \
    -annotationFile $dataDir/reference/genes.gtf \
    -imageRecordFile $dataDir/image/SS200000135TL_D1_20220527_201353_1.1.0.ipr \
    -imageCompressedFile $dataDir/image/SS200000135TL_D1_20220527_201353_1.1.0.tar.gz \
    -sif /media/duo36t/reference/SAW_v5.4.0.sif \
    -threads 16 \
    -doCellBin Y \
    -outDir $outDir 

```

I didn't use the path of `/media/duo36t/test/SAW-pipeline`, why it caused an error?

**Comment by TheSallyGardens** [comment]
Does the /media/duo36t/test/SAW-pipeline path exist? If it does not exist, please create it.

**Comment by Feng-Zhang** [comment]
Yes, it exist. By the way, the output path under the path caused the error is no problem, which is /media/duo36t/test/SAW-pipeline/result.

发件人: ***@***.***>
发送时间: 2022年12月26日 8:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [BGIResearch/SAW] How to debug using SAW_v5 version? (Issue #24)


Does the /media/duo36t/test/SAW-pipeline path exist? If it does not exist, please create it.

―

**Comment by TheSallyGardens** [comment]
Try export SINGULARITY_BIND=/media/duo36t/test/SAW-pipeline on the terminal

**Comment by Feng-Zhang** [comment]
I have tried ` export SINGULARITY_BIND=/media/duo36t/test/SAW-pipeline ` on the terminal and in the script 1_saw_test.sh, but I get the same error.

**Comment by TheSallyGardens** [comment]
I can't reproduce your problem.Can you tell me your SINGULARITY version  and send files were created under the output path？

**Comment by Feng-Zhang** [comment]
I tried to debug this issue and found that the parameter `${read1List[i]}` is `...` when `i` equal to 1. 
When i is 0, the mapping process run well, and the parameter file is :
```
cat E100026571_L01_trim_read_1.bcPara 
in=/media/zhangfeng/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/mask/SS200000135TL_D1.barcodeToPos.h5
in1=/media/zhangfeng/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reads/E100026571_L01_trim_read_1.fq.gz
in2=/media/zhangfeng/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/reads/E100026571_L01_trim_read_2.fq.gz
encodeRule=ACTG
action=4
barcodeReadsCount=/media/zhangfeng/duo36t/test/SAW_pipeline/result/00.mapping/E100026571_L01_trim_read_1.barcodeReadsCount.txt
platform=T10
out=E100026571_L01_trim_read_1
barcodeStart=0
barcodeLen=25
umiStart=25
umiLen=10
umiRead=1
mismatch=1
bcNum=645784920
polyAnum=15
mismatchInPolyA=2
```
However, when i is 1, the parameter file became `...`: 
```
cat .bcPara 
in=/media/zhangfeng/duo36t/reference/SAW_Demo_Data/SS200000135TL_D1_v5/mask/SS200000135TL_D1.barcodeToPos.h5
in1=...
in2=...
encodeRule=ACTG
action=4
barcodeReadsCount=/media/zhangfeng/duo36t/test/SAW_pipeline/result/00.mapping/.barcodeReadsCount.txt
platform=T10
out=
barcodeStart=0
barcodeLen=25
umiStart=25
umiLen=10
umiRead=1
mismatch=1
bcNum=645784920
polyAnum=15
mismatchInPolyA=2

```

**Comment by TheSallyGardens** [comment]
If more than one lane sequencing data was given：
    -fq1 $dataDir/reads/E100026571_L01_trim_read_1.fq.gz,$dataDir/reads/E100026571_L02_trim_read_1.fq.gz,$dataDir/reads/E100026571_L03_trim_read_1.fq.gz \
    -fq2 $dataDir/reads/E100026571_L01_trim_read_2.fq.gz,$dataDir/reads/E100026571_L02_trim_read_1.fq.gz,$dataDir/reads/E100026571_L03_trim_read_2.fq.gz \

**Comment by Feng-Zhang** [comment]
Thank you a lot. I have got all results. 
There is a quick question for confirmation. The code for calculating genome file size in GB is used for Genome file, not the genome.fa file, is it?
```
ls -l --block-size=GB STAR_SJ100/Genome 
-rw-r--r-- 1 xx xx 3GB 9月  13 18:14 STAR_SJ100/Genome
```
Therefore, genomeSize is `-genomeSize 3` ?

**Comment by TheSallyGardens** [comment]
> Thank you a lot. I have got all results. There is a quick question for confirmation. The code for calculating genome file size in GB is used for Genome file, not the genome.fa file, is it?
> 
> ```
> ls -l --block-size=GB STAR_SJ100/Genome 
> -rw-r--r-- 1 xx xx 3GB 9月  13 18:14 STAR_SJ100/Genome
> ```
> 
> Therefore, genomeSize is `-genomeSize 3` ?
Yes! 
Enjoy it (:
