### ISSUE TITLE
Error in generating report file.

### ISSUE THREAD

**Issue by UmaSangumathi** [BGIResearch/SAW#25]
Hi, Thanks for the Workflow. I am running SAW_v5.4.0_workflow and I get error in the final step of report generation. The intermediate step generated tissue.gef looks ok. Please let me know how to fix the report generation, and below is the error message. 

Wed 21 Dec 2022 05:23:09 PM +08 => report generation start......
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2103: FutureWarning: The `axis` variable is no longer used and will be removed. Instead, assign variables directly to `x` or `y`.
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2103: FutureWarning: The `axis` variable is no longer used and will be removed. Instead, assign variables directly to `x` or `y`.
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
  warnings.warn(msg, FutureWarning)
/usr/local/python3/lib/python3.8/site-packages/seaborn/distributions.py:2103: FutureWarning: The `axis` variable is no longer used and will be removed. Instead, assign variables directly to `x` or `y`.
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1255, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "v2.1.1/handleReport_main.py", line 345, in <module>
  File "v2.1.1/handleReport_main.py", line 292, in main
  File "v2.1.1/generate_analysis_report.py", line 207, in generate_html_function
  File "v2.1.1/generate_analysis_report.py", line 904, in get_small_images
  File "v2.1.1/generate_analysis_report.py", line 937, in image_array_to_base64
  File "v2.1.1/generate_analysis_report.py", line 943, in image2base64
  File "/usr/local/python3/lib/python3.8/site-packages/PIL/Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "/usr/local/python3/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1257, in _save
    raise OSError(f"cannot write mode {mode} as PNG") from e
OSError: cannot write mode F as PNG

Best,
Uma

**Comment by TheSallyGardens** [comment]
Hello, could you provide running code?

**Comment by UmaSangumathi** [comment]
Hi @TheSallyGardens, Please let me know if you require any other details. Thanks

export SINGULARITY_BIND=$dataDir,$outDir,$softwareDir,$refDir,$imageDir

bash $softwareDir/SAW/script/stereoPipeline_v5.4.0.sh -genomeSize 2.79 -splitCount 1 -maskFile X.barcodeToPos.h5 \
      -fq1 _1.fq.gz,_1.fq.gz,_1.fq.gz,_1.fq.gz,_1.fq.gz,_1.fq.gz,_1.fq.gz  \
        -fq2 _2.fq.gz,_2.fq.gz,_2.fq.gz,_2.fq.gz,_2.fq.gz,_2.fq.gz,_2.fq.gz,_2.fq.gz  \
        -speciesName Mouse   -tissueType X -refIndex $refDir/STAR_SJ100 -annotationFile $refDir/genes/genes.gtf \
        -imageRecordFile $imageDir/*.ipr -imageCompressedFile $imageDir/*.tar.gz \
        -sif $softwareDir/SAW_v5.4.0.sif -threads 20 -doCellBin Y -outDir $outDir

**Comment by TheSallyGardens** [comment]
Hi@UmaSangumathi ,could you provide the following documents to email (tangdecong@genomics.cn)? Thank you !
1、$imageDir/.tar.gz
2、$outDir/03.register/{SN}.rpi
