### ISSUE TITLE
Can not find the Chip T mask file of fly stereo-seq data

### ISSUE THREAD

**Issue by nieyage** [BGIResearch/SAW#29]
I was interested in the fly stereo-seq data in article "High-resolution 3D spatiotemporal transcriptomic maps of developing Drosophila embryos and larvae", but I didn't find the available Chip T mask file in https://db.cngb.org/stomics/flysta3d/ .

Can anyone give me some advice?

 Thanks for the help!

**Comment by TheSallyGardens** [comment]
Hi!
Please contact the author of this article.
