### ISSUE TITLE
singularity build error: While performing build: conveyor failed to get: reading manifest 05.5.0 in docker.io/stomics/saw: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by ViHammer** [BGIResearch/SAW#30]
Hi there,

when running the following command:
`singularity build SAW_v5.5.0.sif docker://stomics/saw:05.5.0`
as described in chapter "Quick download SAW from DockerHub" I get the following error message:
```
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: reading manifest 05.5.0 in docker.io/stomics/saw: manifest unknown: manifest unknown
```

Thanks in advance!

**Comment by TheSallyGardens** [comment]
@ViHammer  Hi,Please try using:
singularity build SAW_v5.5.2.sif docker://stomics/saw:05.5.2

**Comment by ViHammer** [comment]
That fixed it. 
Issue can be closed once the Read.me is edited.
