### ISSUE TITLE
About the password

### ISSUE THREAD

**Issue by Biomamba** [BGIResearch/SAW#34]
Dear author:
  Thank you for your excellent pipepline for stereo-Seq. Could you please tell me the  password of test data(http://116.6.21.110:8090/share/QJKAO6hGUpTPbuYH7Dvi)? Thank you!

Best regards!

**Comment by TheSallyGardens** [comment]
@Biomamba  Hi,this password is public.
![image](https://user-images.githubusercontent.com/40382381/225564456-e2026723-0147-4846-8e48-21b2797d1be9.png)

**Comment by Biomamba** [comment]
> @Biomamba Hi,this password is public. ![image](https://user-images.githubusercontent.com/40382381/225564456-e2026723-0147-4846-8e48-21b2797d1be9.png)

Got it! Thank you for your goodness!
