### ISSUE TITLE
user namespace issue

### ISSUE THREAD

**Issue by gangcai** [BGIResearch/SAW#5]
While executing following codes:

`singularity exec <SAW_v4.1.0.sif> mapping --runMode genomeGenerate \
    --genomeDir reference/STAR_SJ100 \
    --genomeFastaFiles reference/genome.fa \
    --sjdbGTFfile reference/genes.gtf \
    --sjdbOverhang 99 \
    --runThreadN 12`

Errors occurred:
"SAW_v4.1.0.sif: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled"

**Comment by qiqiHE93** [comment]
bug your HPC admins to install Singularity

info from https://stackoverflow.com/questions/69375369/how-to-run-singularity-container-on-hpc-cluster-error-failed-to-create-user

**Comment by liangzhenhou** [comment]
> bug your HPC admins to install Singularity
> 
> info from https://stackoverflow.com/questions/69375369/how-to-run-singularity-container-on-hpc-cluster-error-failed-to-create-user

For a non-root user, could you provide another way to handle this problem?
