### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by tyyl622** [BGIResearch/SAW#7]
Hi, I want to know how can I install Singularity and SAW without root? 
If root is necessary, maybe developing a version without root, just like spaceranger or cellranger of 10 ×, is easier use.
Thanks!

**Comment by Clouate** [comment]
Hi, you can try to install Singularity without root using command like this
'./mconfig --without-suid --prefix=$PATH_YOU_WANT_TO_INSTALL' .
And SAW is a package executed by Singularity, root is not necessary.

**Comment by tyyl622** [comment]
Got it! Thank you so much~ I will try as your suggestion~
