### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0: 

### ISSUE THREAD

**Issue by Ed2uiz** [BGIResearch/SAW#8]
Hello,

I'm trying to run the SAW pipeline on a subset of the SN.h5 file. I am using h5py to read the original SN.h5 file downloaded from the MOSTA website, selecting a region of interest from this file, and writing this to a new SN_subset.h5 file. I am unable to run the SAW pipeline when I use this SN_subset.h5 file though, see error below. Is there a way to run the SAW pipeline for a subset of the barcodes in the original SN.h5 matrix? 

 ```
~~~ pre-mapping CIDcount ~~~
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 1017 in H5Dget_num_chunks(): Can't get number of chunks
    major: Dataset
    minor: Can't get value
  #001: H5VLcallback.c line 2434 in H5VL_dataset_optional(): unable to execute dataset optional callback
    major: Virtual Object Layer
    minor: Can't operate on object
  #002: H5VLcallback.c line 2398 in H5VL__dataset_optional(): unable to execute dataset optional callback
    major: Virtual Object Layer
    minor: Can't operate on object
  #003: H5VLnative_dataset.c line 461 in H5VL__native_dataset_optional(): not a chunked dataset
    major: Invalid arguments to routine
    minor: Inappropriate type

```

**Comment by qiqiHE93** [comment]
hi~ we'd like to know which version of saw you mentioned here.

**Comment by qiqiHE93** [comment]
.h5 file with non-chunk structure is not supported in saw pipeline at the moment, and we will improve the software in future ~
