### ISSUE TITLE
tags in bam file

### ISSUE THREAD

**Issue by lqwszbd** [BGIResearch/SAW#9]
Hi！
I need the tag"CID" to follow up on the bam file, but only "Cx" and "Cy" are in the bam file.
How should I make the tag “CID” appear in the bam file?
Thanks!

**Comment by qiqiHE93** [comment]
see below site for more detail.
https://github.com/BGIResearch/SAW/blob/main/Manual/STOmics%E5%88%86%E6%9E%90%E6%B5%81%E7%A8%8B%E7%BB%93%E6%9E%9C%E6%96%87%E4%BB%B6.pdf
